class leftBuilder{
    constructor(){
        this.output = {
            topnav1:false,
            topnav2:false,
            service : true,
            serviceChild:{
                ethnicities:true,
                ethnicitiesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                services:true,
                servicesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                service_categoryies:true,
                service_categoryiesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                service_subcategories:true,
                service_subcategoriesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                hairtype_categories:true,
                hairtype_categoriesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                hairtype_subcategories:true,
                hairtype_subcategoriesChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                }
            },
            user:true,
            userChild:{
                salesPerson:true,
                salesPersonChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                salons:true,
                salonsChild:{
                    create:true,
                    view:true,
                    edit:true,
                    delete:true,
                },
                admin:false,
                adminChild:{
                    create:false,
                    view:false,
                    edit:false,
                    delete:true,
                },
                users:true,
                usersChild:{
                    create:false,
                    view:true,
                    edit:true,
                    delete:true,
                }
            },
            salonTab:true,
            salonTabChild:{},
            misc:true,
            miscChild:{
                permission:true,
                setting:true
            }
        }
    }
    inlet(data){
        console.log(JSON.stringify(this.output));
    }
}
module.exports = leftBuilder